import pytest

from valiss import ValissError, creds, nkeys


def test_roundtrip_account_creds():
    account = nkeys.create_account()
    c = creds.Creds(account_token="acct.token.sig", seed=account.seed)
    parsed = creds.parse(c.format())
    assert parsed == c
    assert parsed.signer().public_key == account.public_key


def test_roundtrip_user_bundle():
    user = nkeys.create_user()
    c = creds.Creds(
        account_token="acct.token.sig", user_token="user.token.sig", seed=user.seed
    )
    parsed = creds.parse(c.format())
    assert parsed == c


def test_roundtrip_user_creds_without_account_token():
    user = nkeys.create_user()
    c = creds.Creds(user_token="user.token.sig", seed=user.seed)
    parsed = creds.parse(c.format())
    assert parsed == c


def test_roundtrip_bearer_creds():
    c = creds.Creds(account_token="acct.token.sig", user_token="user.token.sig")
    parsed = creds.parse(c.format())
    assert parsed == c
    assert parsed.signer() is None
    assert "IMPORTANT" not in c.format()


def test_parse_requires_a_token():
    with pytest.raises(ValissError, match="no token markers found"):
        creds.parse("just some text")


def test_parse_rejects_empty_section():
    content = "-----BEGIN VALISS ACCOUNT TOKEN-----\n------END VALISS ACCOUNT TOKEN------\n"
    with pytest.raises(ValissError, match="no content before"):
        creds.parse(content)


def test_parse_rejects_unclosed_section():
    with pytest.raises(ValissError, match="not closed"):
        creds.parse("-----BEGIN VALISS ACCOUNT TOKEN-----\n")


def test_parse_ignores_surrounding_noise():
    c = creds.Creds(account_token="acct.token.sig")
    contents = "# generated by valiss\n\n" + c.format() + "\ntrailing garbage\n"
    assert creds.parse(contents).account_token == "acct.token.sig"


def test_load(tmp_path):
    account = nkeys.create_account()
    c = creds.Creds(account_token="acct.token.sig", seed=account.seed)
    path = tmp_path / "acme.creds"
    path.write_text(c.format())
    assert creds.load(str(path)) == c


def test_load_missing_file():
    with pytest.raises(ValissError, match="read creds"):
        creds.load("/nonexistent/path.creds")


def test_signer_rejects_malformed_seed():
    c = creds.Creds(account_token="acct.token.sig", seed="not-a-seed")
    with pytest.raises(ValissError, match="creds seed"):
        c.signer()
